# 00 - Pytorch Fundamentals

In [1]:
import torch
torch.__version__

'2.5.1+cu121'

1. Creating Tensors

In [4]:
# Create Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Check Dimension
scalar.ndim

0

In [6]:
# Retrieve Number from Tensor (Convert Tensor to Scalar)
scalar.item()

7

In [16]:
# Create Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

# Create Matrix
MATRIX = torch.tensor(
    [
    [7,7],
    [8,9]
    ]
)

print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

# Create Tensor
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([7, 7])
1
torch.Size([2])
tensor([[7, 7],
        [8, 9]])
2
torch.Size([2, 2])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([2, 3, 3])


In [18]:
# Create random Tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1040, 0.8833, 0.9240, 0.1417],
         [0.1707, 0.7054, 0.9007, 0.1183],
         [0.2122, 0.7503, 0.0953, 0.4835]]),
 torch.float32)

In [20]:
print(torch.zeros(size=(3,4)))
print(torch.ones(size=(3,4)))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
# Arangement
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # float_32 as default
                               device = None, # CPU or GPU
                               requires_grad = False, # If yes, operations performed are recorded for back prop
                               )

# Three attributes to be aware of when debugging
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [35]:
# Operations
TENSOR = torch.tensor([1,2,3])
print(TENSOR + 10)
print(TENSOR * 10)
print(TENSOR * TENSOR) # Element-wise
print(torch.matmul(TENSOR, TENSOR)) # Matrix Multiplication

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([1, 4, 9])
tensor(14)


In [36]:
### Linear Layer

# Initialize the random number generator with a fixed seed to ensure the linear layer's weights are initialized consistenly across runs.
torch.manual_seed(42)

# Create a fully connected (dense) layer which accepts 2-dimensional input vector and outputs 6-dimensional output vectors. This layer has
#   Weight matrix: Shape (6,2) (randomly initialized)
#   Bias: Shape (6,) (randomly initialized)
linear = torch.nn.Linear(in_features = 2, out_features = 6)

x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)

# Performs the linear transform operation:
#   output = x @ linear.weight.T + linear.bias
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [37]:
### Aggregation

x = torch.arange(0,100,10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [2]:
### Positional min/max
v = torch.arange(10, 100, 10)
print(f"Tensor: {v}")

# Returns index of max and min values
print(f"Index where max value occurs: {v.argmax()}")
print(f"Index where min value occurs: {v.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [5]:
### Type change
tensor = torch.arange(10., 100., 10.)

# Create a float16 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [6]:
### Tensor Manipulation
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [8]:
x_reshaped = x.reshape(1,7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [11]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [12]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [13]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [15]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 256, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 256, 3])
New shape: torch.Size([3, 224, 256])


In [19]:
### Indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)

print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [20]:
print(x[:, 0])
print(x[:, :, 1])
print(x[:, 1, 1])
print(x[0, 0, :])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [21]:
# nparray to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [22]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [23]:
### Reproducibility
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [25]:
# Set device type (CPU or GPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [29]:
tensor = torch.tensor([1,2,3], device = device)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

# Exercises

In [38]:
import torch

# Seed CPU (affects NumPy and CPU-based PyTorch operations)
torch.manual_seed(42)

# Seed the current CUDA GPU
torch.cuda.manual_seed(42)

# Seed all CUDA GPUs (if using multiple GPUs)
torch.cuda.manual_seed_all(42)

In [39]:
# Exercise 2: Create a random tensor with shape (7, 7).
x = torch.randn(size=(7,7))
x, x.shape

(tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431],
         [-1.6047, -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594],
         [-0.7688,  0.7624,  1.6423, -0.1596, -0.4974,  0.4396, -0.7581],
         [ 1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347],
         [-0.2316,  0.0418, -0.2516,  0.8599, -1.3847, -0.6581,  0.0780],
         [ 0.5258, -0.4880,  1.1914, -0.8140, -0.7360, -0.8371,  0.0360],
         [-0.0635,  0.6756, -0.0978,  1.8446, -1.1845,  1.3835, -1.2024]]),
 torch.Size([7, 7]))

In [40]:
# Exercise 3: Perform a matrix multiplication on the tensor from 2 with another
#             random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

y = torch.randn(size=(1,7))
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[ 5.7713],
         [-0.2804],
         [-0.6681],
         [-3.0184],
         [ 1.6454],
         [ 1.5024],
         [-1.3706]]),
 torch.Size([7, 1]))

In [43]:
# Exercise 6: Create two random tensors of shape (2, 3) and send them both to the GPU
x = torch.randn(size=(2,3)).to(device)
y = torch.randn(size=(2,3), device = device)

In [44]:
# Exercise 7: Perform a matrix multiplication on the tensors you created in 6
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[ 0.5634, -1.6996],
         [-3.0597,  1.4679]]),
 torch.Size([2, 2]))

In [45]:
# Exercise 8,9: Find the maximum and minimum values and index values of the output of 7.
print(f"Max: {z.max()}")
print(f"Min: {z.min()}")
print(f"Max Index: {z.argmax()}")
print(f"Min Index: {z.argmin()}")

Max: 1.4679492712020874
Min: -3.059729814529419
Max Index: 3
Min Index: 2


In [49]:
# Exercise 10: Make a random tensor with shape (1, 1, 1, 10)
#              and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10)

torch.cuda.manual_seed(7)

z = torch.randn(size=(1,1,1,10)).to(device)
z = torch.squeeze(z)
z, z.shape

(tensor([-0.5966,  0.1820, -0.8567,  1.1006, -1.0712,  0.1227, -0.5663,  0.3731,
         -0.8920, -1.5091]),
 torch.Size([10]))